Upgrade to mobx 6
rakenapp/mobx-mc pull request #44
Opened 2021-06-04 01:15 UTC by trenthogan

Upgrade to Mobx 6.

**A few notes from dev:**

toJS no longer takes any options. It no longer converts Maps and Sets to plain data structures. Generic, flexible serialization of data structures is out of scope for the MobX project, and writing custom serialization methods is a much more scalable approach to serialization (tip: leverage computeds to define how class instances should be serialized).

So we had to refactor to use: Object.fromEntries instead

runInAction no longer supports passing a name as first argument. Name the original function or use action(name, fn)() if you care about the debug name.

Jest seemed to loose the ability to look at spys on class prototypes without saving the spy to a var and checking that.

Thanks to @nickryall for help

2021-06-04 02:48 UTC, interstellarbox approved these changes

2021-06-04 02:52 UTC, nickryall requested changes

2021-06-04 05:41 UTC, trenthogan commented
Changes updated

2021-06-08 07:29 UTC, nickryall approved these changes

2023-11-27 07:31 UTC, closed without merging